=== Mission-KI/pruefplattform/barebone/src/mki_barebone/toolspec_validation/toolspec_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "required": ["domain", "name"]
        },
        "description": {
            "type": "string"
        },
        "functions": {
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z0-9_]+$": {
                    "type": "object",
                    "properties": {
                        "project": {
                            "type": "string"
                        },
                        "package": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "path": {
                                    "type": "string"
                                }
                            },
                            "required": ["name", "path"]
                        },
                        "script": {
                            "type": "string"
                        },
                        "function": {
                            "type": "string"
                        },
                        "inputs": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "type": {
                                        "type": "string"
                                    },
                                    "format": {
                                        "type": "string"
                                    },
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "$schema": {
                                                "type": "string"
                                            },
                                            "type": {
                                                "type": "string"
                                            },
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "type": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        },
                                        "required": ["$schema", "type"]
                                    },
                                    "description": {
                                        "type": "string"
                                    }
                                },
                                "required": ["name", "type", "format", "schema", "description"]
                            }
                        },
                        "outputs": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "type": {
                                        "type": "string"
                                    },
                                    "format": {
                                        "type": "string"
                                    },
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "$schema": {
                                                "type": "string"
                                            },
                                            "type": {
                                                "type": "string"
                                            }
                                        },
                                        "required": ["$schema", "type"]
                                    },
                                    "description": {
                                        "type": "string"
                                    }
                                },
                                "required": ["name", "type", "format", "schema", "description"]
                            }
                        }
                    },
                    "required": ["project", "package", "script", "function", "inputs", "outputs"]
                }
            }
        },
        "build": {
            "type": "object",
            "properties": {
                "requirements": {
                    "type": "string"
                }
            },
            "required": ["requirements"]
        }
    },
    "required": ["id", "description", "functions", "build"]
}

=== Mission-KI/pruefplattform/barebone/tests/toolspec_test/spec_ref1.json
{
    "id": {
        "domain": "d",
        "name": "m"
    },
    "description": "desc",
    "functions": {
        "a": {
            "project": "",
            "package": {
                "name": "n",
                "path": "p/p"
            },
            "script": "s.py",
            "function": "f",
            "inputs": [
                {
                    "name": "a",
                    "type": "file",
                    "format": "json",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    },
                    "description": "array of numbers a"
                },
                {
                    "name": "b",
                    "type": "file",
                    "format": "json",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    },
                    "description": "array of numbers b"
                }
            ],
            "outputs": [
                {
                    "name": "c",
                    "type": "file",
                    "format": "json",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "number"
                    },
                    "description": "float c"
                }
            ]
        }
    },
    "build": {
        "requirements": "requirements.txt"
    }
}

=== Mission-KI/pruefplattform/nodes/scikit-logreg-model/tests/context/args/spec.json
{
    "id": {
        "domain": "local",
        "name": "scikit-logreg-model"
    },
    "description": "A logistic regression model with fixed parameters",
    "functions": {
        "predict": {
            "project": "scikit-logreg-model",
            "package": {
                "name": "logreg_model_wrapper",
                "path": "src/enpkg/logreg_model_wrapper"
            },
            "script": "impl.py",
            "function": "predict_wrapper",
            "inputs": [
                {
                    "name": "features",
                    "type": "file",
                    "format": "application/json",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "type": "number"
                            }
                        }
                    },
                    "description": "An array representing a batch of model inputs"
                }
            ],
            "outputs": [
                {
                    "name": "predictions",
                    "type": "file",
                    "format": "application/json",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "number"
                        }
                   },
                    "description": "An array representing a batch of model predictions."
                }
            ]
        }
    },
    "build": {
        "requirements": ""
    }
}

=== Mission-KI/pruefplattform/barebone/tests/toolspec_test/spec_ref2.json
{
    "id": {
        "domain": "d",
        "name": "m"
    },
    "description": "desc",
    "functions": {
        "a": {
            "project": "",
            "package": {
                "name": "n",
                "path": "p/p"
            },
            "script": "s.py",
            "function": "f",
            "inputs": [],
            "outputs": []
        }
    },
    "build": {
        "requirements": "requirements.txt"
    }
}

=== Mission-KI/pruefplattform/barebone/tests/nodes/mocktool/tests/context/grpc/spec.json
{
    "id": {
        "domain": "local",
        "name": "mocktool"
    },
    "description": "A mock tool for development",
    "functions": {
        "fourtyone": {
            "project": "mocktool",
            "package": {
                "name": "toolpkg",
                "path": "src/enpkg/toolpkg"
            },
            "script": "metric.py",
            "function": "fourtyone_wrapper",
            "inputs": [],
            "outputs": [
                {
                    "name": "result",
                    "type": "file",
                    "format": "application/json",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "integer"
                    },
                    "description": "A value of 41."
                }
            ]
        },
        "fourtytwo": {
            "project": "toolproj",
            "package": {
                "name": "toolpkg",
                "path": "src/enpkg/toolpkg"
            },
            "script": "metric.py",
            "function": "fourtytwo_wrapper",
            "inputs": [],
            "outputs": [
                {
                    "name": "result",
                    "type": "file",
                    "format": "json",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "integer"
                    },
                    "description": "A value of 42."
                }
            ]
        }
    },
    "build": {
        "requirements": ""
    }
}
